name: jupyter_sandbox
channels:
  - defaults
dependencies:
  - pip
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  # https://github.com/conda/conda/issues/2800
  # https://stackoverflow.com/questions/47887224/anaconda-install-specific-packages-from-specific-channels-using-environment-yml
  - conda-forge::watermark
